### ISSUE TITLE
[MSHARED-134] Using ${artifcactId}-Extention-Name in MANIFEST file can create invalid MANIFEST files

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archiver#133]
**[Todd Caine](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eniact)** opened **[MSHARED-134](https://issues.apache.org/jira/browse/MSHARED-134?redirect=false)** and commented

If you have a maven dependency on an something with an artifactId that contains a '.'  in it, it creates an illegal manifest file when trying to create an executable jar file (java -jar foo.jar).

```
Exception in thread "main" java.io.IOException: invalid header field name: geronimo-jms_1.1_spec-Extension-Name
        at java.util.jar.Attributes.read(Attributes.java:409)
        at java.util.jar.Manifest.read(Manifest.java:167)
        at java.util.jar.Manifest.<init>(Manifest.java:52)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:158)
        at java.util.jar.JarFile.getManifest(JarFile.java:145)
```

Here's my configuration:

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <configuration>
    <archive>
      <manifest>
        <mainClass>my.class.Test</mainClass>
        <addClasspath>true</addClasspath>
        <addExtensions>true</addExtensions>
        <classpathPrefix>./lib/</classpathPrefix>
      </manifest>
    </archive>
  </configuration>
</plugin>
```

I added the following dependency:

```xml
<dependency>
  <groupId>org.apache.geronimo.specs</groupId>
  <artifactId>geronimo-jms_1.1_spec</artifactId>
</dependency>
```

When the maven-archiver tries to create a manifest file with the JARs dependencies it adds the following to the META-INF/MANIFEST.MF file:

```
geronimo-jms_1.1_spec-Extension-Name: geronimo-jms_1.1_spec
geronimo-jms_1.1_spec-Implementation-Version: 1.0
```

After digging around a bit it turns out that '.' is an illegal character in the "Extension-Name" and "Implementaion-Version" header fields, which leads to the following exception when I try to run "java -jar Test.jar"

java.io.IOException: invalid header field name: geronimo-jms_1.1_spec-Extension-Name

---

**Affects:** maven-archiver-2.4

**Attachments:**
- [MavenArchiver.java-Patch.txt](https://issues.apache.org/jira/secure/attachment/12719065/MavenArchiver.java-Patch.txt) (_1.60 kB_)
- [nautilus-debug-log.txt](https://issues.apache.org/jira/secure/attachment/12719130/nautilus-debug-log.txt) (_188.00 kB_)

**Issue Links:**
- [MSHARED-99](https://issues.apache.org/jira/browse/MSHARED-99) Archiver should validate manifest attribute names.

6 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Sridhar Komandur](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=komandur)** commented

Please find the attached patch file that fixes this issue by replacing '.' with '_' in the artifactId

**Comment by jira-importer** [comment]
**[Sridhar Komandur](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=komandur)** commented

(for some reason my attachment from last night does not show, so 'attach'ing again)

**Comment by jira-importer** [comment]
**[Chris Beach](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chrisbeach)** commented

This issue is preventing my Maven-built project from running. I'm using Apache Axis2, which has transitive dependencies on Geronimo.

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Fixed with testcase in r1235286
